// <auto-generated />
using System;
using Final___Magix.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Final___Magix.Migrations
{
    [DbContext(typeof(CardContext))]
    partial class CardContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Final___Magix.Models.BulkData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.ToTable("BulkData");

                    b.HasData(
                        new
                        {
                            Id = "ed4cc273-adc3-4f46-9743-134b552d1d56",
                            Name = "Balthor the Defiled"
                        },
                        new
                        {
                            Id = "b0244a1f-e696-4223-9c14-22c2ca3cb738",
                            Name = "Herd Migration"
                        },
                        new
                        {
                            Id = "7bd0e025-7a75-4641-a51a-27df9dcde05f",
                            Name = "Crawling Barrens"
                        },
                        new
                        {
                            Id = "c777432f-7965-4ad8-8d53-93919ae767d4",
                            Name = "Primal Whisperer"
                        },
                        new
                        {
                            Id = "cc61a398-cf16-415b-b3cf-897217dc7cc9",
                            Name = "Sonic Assault"
                        },
                        new
                        {
                            Id = "e6246cf3-76bd-476b-9cd9-789b6ad48887",
                            Name = "Kheru Mind-Eater"
                        },
                        new
                        {
                            Id = "785e1a67-af94-48e8-bb37-4999d1fb4c66",
                            Name = "Phyrexian Bloodstock"
                        },
                        new
                        {
                            Id = "1fe7a4f0-d677-4ae2-883c-eb46d0999584",
                            Name = "Messenger Jays"
                        },
                        new
                        {
                            Id = "a20f5392-5cde-4326-a322-7463ec4b0515",
                            Name = "Silverfur Partisan"
                        },
                        new
                        {
                            Id = "14aa4474-96a0-4c1d-a09d-73b9c1073b00",
                            Name = "Scrapheap"
                        },
                        new
                        {
                            Id = "db0489ee-96b6-4437-a716-ee07ecbd4cb7",
                            Name = "Knighted Myr"
                        },
                        new
                        {
                            Id = "7a9d23d5-2f94-48e6-824f-f1de8f742989",
                            Name = "Ulvenwald Observer"
                        },
                        new
                        {
                            Id = "77ceba8b-de19-4db8-b5a7-f5df49bf241f",
                            Name = "Old Gnawbone"
                        },
                        new
                        {
                            Id = "abe8eefe-c9f8-43f7-a348-8afee8b0ec68",
                            Name = "Ability Punchcard"
                        },
                        new
                        {
                            Id = "f928e8e8-aa20-402c-85bd-59106e9b9cc7",
                            Name = "Leave // Chance"
                        },
                        new
                        {
                            Id = "29214308-711a-490f-8e93-bf61baf1749c",
                            Name = "Karona's Zealot"
                        },
                        new
                        {
                            Id = "3cda5434-c0a5-4551-8e30-b1923f0001b8",
                            Name = "Kuldotha Ringleader"
                        },
                        new
                        {
                            Id = "3b045121-7742-41ee-be27-591692f42331",
                            Name = "Necromancer's Magemark"
                        },
                        new
                        {
                            Id = "0050dd40-9a18-41e4-97e6-fce5bf220ccf",
                            Name = "Security Rhox"
                        },
                        new
                        {
                            Id = "248d71f9-89ef-492e-a854-a890f7d91ef8",
                            Name = "Spellbinding Soprano"
                        },
                        new
                        {
                            Id = "9cb19ac2-edf9-4f9a-b9ba-2a33ba96a4d8",
                            Name = "Piracy Charm"
                        },
                        new
                        {
                            Id = "53cc3197-7a69-4b96-a701-aa3c54543958",
                            Name = "Ogre Painbringer"
                        },
                        new
                        {
                            Id = "2ab08d69-210b-4b06-88a2-45281a1a4e1e",
                            Name = "Stinkweed Imp"
                        },
                        new
                        {
                            Id = "da55c6a1-1f26-4254-ac62-fdbe94278de5",
                            Name = "Diviner's Lockbox"
                        },
                        new
                        {
                            Id = "db9103c9-084f-4ad2-8b7b-ca52be97619d",
                            Name = "Skyclave Geopede"
                        },
                        new
                        {
                            Id = "af443b8c-203f-46f0-9233-60f962e5baa6",
                            Name = "Pygmy Giant"
                        },
                        new
                        {
                            Id = "9af69b5e-f713-4af6-9990-f99be7801f73",
                            Name = "Curse of the Forsaken"
                        },
                        new
                        {
                            Id = "c9d9378d-e553-48b5-8a23-59a35329eda2",
                            Name = "Daring Thief"
                        },
                        new
                        {
                            Id = "bbf9a803-473a-4c38-b352-d47c4fd93d5e",
                            Name = "Reach of Shadows"
                        },
                        new
                        {
                            Id = "076e7c58-a6fe-4882-8f8d-698be9a7f22d",
                            Name = "Mental Vapors"
                        },
                        new
                        {
                            Id = "a8ec9be6-c8ad-4a82-8253-c49cdb9443ba",
                            Name = "Dramatic Finale"
                        },
                        new
                        {
                            Id = "4501c6a1-37b8-4009-9c9b-69f0661ca730",
                            Name = "Lukamina, Wolf Form"
                        },
                        new
                        {
                            Id = "c7978371-9ea8-4264-9a2f-38226ea25018",
                            Name = "Obsidian Battle-Axe"
                        },
                        new
                        {
                            Id = "2a1e7796-fbfb-4976-879f-bb748429d5c7",
                            Name = "Brine Hag"
                        },
                        new
                        {
                            Id = "f012f5c8-a974-40a4-9375-071e4d95182a",
                            Name = "Azorius Signet"
                        },
                        new
                        {
                            Id = "c2ce54a3-f3eb-48a0-bfa2-5f4b90e413f0",
                            Name = "Dusk Charger"
                        },
                        new
                        {
                            Id = "f110698e-a343-4eff-ba23-ed7ac5a3f87b",
                            Name = "Akki War Paint"
                        },
                        new
                        {
                            Id = "36a348bb-cdc5-4e2a-933f-21f91faab891",
                            Name = "Audacious Infiltrator"
                        },
                        new
                        {
                            Id = "0daf6a74-57f7-4c44-9413-a28002f3de4c",
                            Name = "Slime Molding"
                        },
                        new
                        {
                            Id = "b3e75332-4f26-42c9-818f-f8f9396b4210",
                            Name = "Ring of Gix"
                        },
                        new
                        {
                            Id = "25283518-cabb-4fa6-ab92-c989190ec9f3",
                            Name = "Stormcloud Djinn"
                        },
                        new
                        {
                            Id = "9d15f7b5-5070-4742-a05c-623822d874fb",
                            Name = "Sivvi's Valor"
                        },
                        new
                        {
                            Id = "f47e5303-c07a-4be0-a314-bf5739a856e5",
                            Name = "Thirsting Axe"
                        },
                        new
                        {
                            Id = "7cc6972a-5305-423f-a936-16ee0fbf9200",
                            Name = "Cruel Deceiver"
                        },
                        new
                        {
                            Id = "7e599847-8ab0-4fd6-b2c0-cb44a7669aa5",
                            Name = "The Locust God"
                        },
                        new
                        {
                            Id = "e0efe5b1-c515-4642-aca2-3eba68fe63ff",
                            Name = "Dhund Operative"
                        },
                        new
                        {
                            Id = "643891b6-23d0-4734-81e0-b315d2d58f50",
                            Name = "Tel-Jilad Fallen"
                        },
                        new
                        {
                            Id = "7fcfe11a-fcc9-41e1-91ef-755bb4e22389",
                            Name = "Ghastly Demise"
                        },
                        new
                        {
                            Id = "829069cf-7e63-4443-b679-65ad15d6ca5e",
                            Name = "Mythic Proportions"
                        },
                        new
                        {
                            Id = "f200ea9a-198b-4ba2-ad2b-ea4a133b7f40",
                            Name = "Necrogoyf"
                        },
                        new
                        {
                            Id = "ad925fb0-1d5c-44a0-8347-202a38c23107",
                            Name = "Iron Maiden"
                        },
                        new
                        {
                            Id = "14e8195a-d0e4-4b11-b413-765ed1cae834",
                            Name = "Delaying Shield"
                        },
                        new
                        {
                            Id = "e51b48e9-a75a-4acd-9462-5e1ac2b0d803",
                            Name = "Slagwoods Bridge"
                        },
                        new
                        {
                            Id = "e7fb8520-1bc4-40e7-a4cc-2933ed7e0c00",
                            Name = "Mazirek, Kraul Death Priest"
                        },
                        new
                        {
                            Id = "726fe2e7-bd1b-4c11-a098-6c8abfbdf06e",
                            Name = "City of Ass"
                        },
                        new
                        {
                            Id = "4ff97c69-6a6b-401c-b0a1-55fa81045d19",
                            Name = "Braids, Arisen Nightmare"
                        },
                        new
                        {
                            Id = "a46e8f6a-3a1a-4c30-9348-4b31882267eb",
                            Name = "Rack and Ruin"
                        },
                        new
                        {
                            Id = "55b6b7f0-d7fc-46b6-99ff-ba8206ecd628",
                            Name = "Ulamog's Despoiler"
                        },
                        new
                        {
                            Id = "adffef78-f776-42d3-ab40-3347c8e5c88b",
                            Name = "Totally Lost"
                        },
                        new
                        {
                            Id = "c7d4c858-5a11-485d-a514-12a6d80459f0",
                            Name = "Body Snatcher"
                        },
                        new
                        {
                            Id = "e9d3500e-09ba-48b6-933f-25b4625b79aa",
                            Name = "Elegant Entourage"
                        },
                        new
                        {
                            Id = "01f842c8-cd6c-4f4d-9aa8-417a92b37867",
                            Name = "Echoing Ruin"
                        },
                        new
                        {
                            Id = "11e78f75-bf58-4c61-9654-c5d355b5e526",
                            Name = "Plow Through Reito"
                        },
                        new
                        {
                            Id = "71a482cf-a1cd-47b5-a76a-08e03965c679",
                            Name = "Dizzying Gaze"
                        },
                        new
                        {
                            Id = "ad34094d-a7ec-4b04-a288-4d4f1a07fc6b",
                            Name = "Backfire"
                        },
                        new
                        {
                            Id = "b9a41cfc-f329-4e69-a785-835f69c7d2ba",
                            Name = "Cartographer's Survey"
                        },
                        new
                        {
                            Id = "0e1263ea-adc9-442b-b13e-9afb69596372",
                            Name = "Hostile Minotaur"
                        },
                        new
                        {
                            Id = "12220d53-3356-4541-aa43-a0de6ed3f7d0",
                            Name = "Barren Glory"
                        },
                        new
                        {
                            Id = "364ed745-0dff-477a-a2c5-987639936337",
                            Name = "Forked Bolt"
                        },
                        new
                        {
                            Id = "cb720ffe-0836-485d-acef-49ce3c48d947",
                            Name = "Half-Elf Monk // Half-Elf Monk"
                        },
                        new
                        {
                            Id = "655c489f-bffb-45a4-8e7c-2d1a35220197",
                            Name = "Smash to Smithereens"
                        },
                        new
                        {
                            Id = "3ca0d060-7bf7-4311-92f4-6cdfef6f85df",
                            Name = "Ritual of Subdual"
                        },
                        new
                        {
                            Id = "08aea6e3-c8a8-4964-b95d-4c639da55de1",
                            Name = "Niblis of the Mist"
                        },
                        new
                        {
                            Id = "6b34af88-bc4e-4ca8-8662-7dc4050c62c5",
                            Name = "Fists of Flame"
                        },
                        new
                        {
                            Id = "bf42524c-97e5-40b2-8a6d-d2a1f0a9eb65",
                            Name = "Keldon Marauders"
                        },
                        new
                        {
                            Id = "9ff08225-82a5-4636-be6a-d38d32f5663f",
                            Name = "Blood Pet"
                        },
                        new
                        {
                            Id = "0e0fa5ab-c4d1-4b2d-ad62-feb651e4b11c",
                            Name = "Thraben Doomsayer"
                        },
                        new
                        {
                            Id = "afe165cd-8ef7-408e-ae56-3c6a0cc4e409",
                            Name = "Fugitive Druid"
                        },
                        new
                        {
                            Id = "5480ac0a-883a-4f73-8e7c-56d64be410a3",
                            Name = "Nine-Fingers Keene"
                        },
                        new
                        {
                            Id = "a17f4b21-6478-407d-b567-2888349f3b66",
                            Name = "Horizon Seeker"
                        },
                        new
                        {
                            Id = "a06eea30-810b-4623-9862-ec71c4bed11a",
                            Name = "Giant Warrior"
                        },
                        new
                        {
                            Id = "c505f1be-4d9f-4536-a3f7-c6e6e19d5678",
                            Name = "Optical Optimizer"
                        },
                        new
                        {
                            Id = "e55ca835-b7f3-497c-b0bc-50a182cabecf",
                            Name = "Myr Galvanizer"
                        },
                        new
                        {
                            Id = "e09e9b65-ff0e-4efe-b96a-ede69c96e2ea",
                            Name = "Carth the Lion"
                        },
                        new
                        {
                            Id = "409bbc0f-dd40-4de5-931b-a1eb2939dc8c",
                            Name = "Wrenn and Six // Wrenn and Six"
                        },
                        new
                        {
                            Id = "42cbad81-152a-435f-9289-f4b6483a059b",
                            Name = "Cradle of Safety"
                        },
                        new
                        {
                            Id = "e72a911e-8291-48ca-bfc6-8907e3b57011",
                            Name = "Open the Way"
                        },
                        new
                        {
                            Id = "e4810919-b379-40db-a68b-a769dd3ee32d",
                            Name = "Shockmaw Dragon"
                        },
                        new
                        {
                            Id = "1640b76d-15d6-4b08-a34b-c5432259d570",
                            Name = "Aether Adept"
                        },
                        new
                        {
                            Id = "88e35c80-6cfe-49fc-8138-562233ccf987",
                            Name = "Erebos's Intervention"
                        },
                        new
                        {
                            Id = "052b743a-456d-49c3-881e-4f30c7645fa5",
                            Name = "Puppet's Verdict"
                        },
                        new
                        {
                            Id = "d21e0516-4430-4292-850b-f5c524d7f8f8",
                            Name = "Shield Mare"
                        },
                        new
                        {
                            Id = "98956e73-04e4-4d7f-bda5-cfa78eb71350",
                            Name = "Anointer Priest"
                        },
                        new
                        {
                            Id = "d651b9e9-d723-4340-a010-d71b2a697e73",
                            Name = "Serpentine Curve"
                        },
                        new
                        {
                            Id = "4df70b14-5d67-4a92-aaba-72480c621d10",
                            Name = "Bolt of Keranos"
                        },
                        new
                        {
                            Id = "2637f860-01dd-4559-97b3-71c2e7cdbca4",
                            Name = "Night Market Aeronaut"
                        },
                        new
                        {
                            Id = "5dee47ab-d603-4346-97f4-a25dc3f47765",
                            Name = "Ancestral Anger"
                        },
                        new
                        {
                            Id = "5526ff6e-c079-4ad4-ac8d-5e26ecacf50d",
                            Name = "Death's Shadow"
                        },
                        new
                        {
                            Id = "0db18acd-36dd-4469-a370-430141858722",
                            Name = "Gyox, Brutal Carnivora"
                        },
                        new
                        {
                            Id = "54ec2cd6-51f6-4e12-af90-fa254f14ad32",
                            Name = "Hornet"
                        },
                        new
                        {
                            Id = "033afbd5-9937-4957-98ba-48e469a490bb",
                            Name = "Miscast"
                        },
                        new
                        {
                            Id = "065e30fe-03e5-4558-8f41-42992b07712e",
                            Name = "Cherubael"
                        },
                        new
                        {
                            Id = "d117ed81-7b5c-4e29-b958-6126d48ac5a6",
                            Name = "Magus of the Bazaar"
                        },
                        new
                        {
                            Id = "374b5d57-fd20-4062-9ec2-24ac557d9dde",
                            Name = "Mina and Denn, Wildborn"
                        },
                        new
                        {
                            Id = "358c18b7-5321-4793-b54a-e48e39548b9c",
                            Name = "Failed Conversion"
                        },
                        new
                        {
                            Id = "070ff479-9d87-4ab6-aaaa-e96b9df0bac4",
                            Name = "Spinning Wheel"
                        },
                        new
                        {
                            Id = "0e893613-423e-409b-9334-292bd252405b",
                            Name = "You Come to the Gnoll Camp"
                        },
                        new
                        {
                            Id = "8a07b3b2-0354-4026-9c7d-24ce06048271",
                            Name = "Hermit Druid Avatar"
                        },
                        new
                        {
                            Id = "e43d959f-6055-4578-a69a-0ec93e993e21",
                            Name = "Armored Wolf-Rider"
                        },
                        new
                        {
                            Id = "dafb963c-18a5-4770-afb9-0121c614de40",
                            Name = "Kiri-Onna"
                        },
                        new
                        {
                            Id = "52118ff1-ad76-4b97-9fdc-6adfe80140f8",
                            Name = "Branchsnap Lorian"
                        },
                        new
                        {
                            Id = "99ad5807-2adc-40d7-b398-d03fd2cd58b9",
                            Name = "Conclave Sledge-Captain"
                        },
                        new
                        {
                            Id = "c75b81b5-5c84-45d4-832a-20c038372bc6",
                            Name = "Wasp"
                        },
                        new
                        {
                            Id = "c6667e4f-f0f6-4416-940a-d03bed75f5a7",
                            Name = "Clown Car"
                        },
                        new
                        {
                            Id = "7520ee10-3ed1-40eb-86a0-3e463a5fba76",
                            Name = "Glint Raker"
                        },
                        new
                        {
                            Id = "3ae69722-9cb9-4fb7-830f-a284d4a72027",
                            Name = "Brazen Upstart"
                        },
                        new
                        {
                            Id = "f4072640-0f9b-4f0a-84cc-eda415cc92e7",
                            Name = "Avenging Hunter"
                        },
                        new
                        {
                            Id = "72204934-f5aa-4559-8f7e-7b0b223580d0",
                            Name = "Spellskite"
                        },
                        new
                        {
                            Id = "9c258aa1-cd9f-45e9-b478-d689b78850cd",
                            Name = "Eye of Yawgmoth"
                        },
                        new
                        {
                            Id = "335867c0-375d-4914-b9ff-032c59079775",
                            Name = "Order of the White Shield"
                        },
                        new
                        {
                            Id = "8f5228dc-ec9d-456f-a89c-1bc592a1bbab",
                            Name = "Ettercap // Web Shot"
                        });
                });

            modelBuilder.Entity("Final___Magix.Models.CardModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Foil")
                        .HasColumnType("bit");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Print")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Set")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TradeInModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TradeInModelId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Final___Magix.Models.InventoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StoreInventory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "url",
                            Name = "Card A",
                            Price = 5.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "url",
                            Name = "Card B",
                            Price = 3.49m,
                            Quantity = 0
                        });
                });

            modelBuilder.Entity("Final___Magix.Models.TradeInModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("TradeIns");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        });
                });

            modelBuilder.Entity("Final___Magix.Models.CardModel", b =>
                {
                    b.HasOne("Final___Magix.Models.TradeInModel", null)
                        .WithMany("Cards")
                        .HasForeignKey("TradeInModelId");
                });

            modelBuilder.Entity("Final___Magix.Models.TradeInModel", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
